// Root server.js for Hostinger
// This file points to the standalone build generated by Next.js
const path = require('path');

// Check if standalone build exists
const standaloneServerPath = path.join(__dirname, '.next', 'standalone', 'server.js');

try {
    // If running in production and standalone exists, use it
    if (process.env.NODE_ENV === 'production') {
        console.log('Starting standalone server...');
        require(standaloneServerPath);
    } else {
        // Fallback for development if someone runs `node server.js`
        const { createServer } = require('http');
        const next = require('next');
        const dev = process.env.NODE_ENV !== 'production';
        const app = next({ dev });
        const handle = app.getRequestHandler();

        app.prepare().then(() => {
            createServer((req, res) => {
                handle(req, res);
            }).listen(process.env.PORT || 3000, () => {
                console.log('> Ready on http://localhost:' + (process.env.PORT || 3000));
            });
        });
    }
} catch (err) {
    console.error('Failed to start server:', err);
    // If standalone doesn't exist, try the standard next start logic
    console.log('Standalone server not found, please run npm run build first.');
}
